services:
  rabbitmq:
    image: rabbitmq:4.2
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mkk
    restart: unless-stopped
    volumes:
      - ./src/mkk:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data: