"""new constrait

Revision ID: 76d0212b1f42
Revises: b82952edfc55
Create Date: 2026-03-30 12:37:36.939677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d0212b1f42'
down_revision: Union[str, Sequence[str], None] = 'b82952edfc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_check_constraint(
        "positive_only",
        "payments",
        "amount > 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
